CREATE TABLE "Animes" (
  "animeID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "season" int,
  "studio" varchar,
  "release_date" date,
  "genre" varchar,
  "episode_count" int,
  "episode_length" int,
  "translator" varchar,
  "director" varchar,
  "poster_link" text
);

CREATE TABLE "Users" (
  "accountID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "telegram_account" varchar,
  "registration_time" timestamp,
  "popular_stats" json
);

CREATE TABLE "ActorsAnimes" (
  "actorAnimeID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "animeID" int,
  "actorID" int,
  "main_character" bool
);

CREATE TABLE "Actors" (
  "actorID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "birthdate" date,
  "country" varchar,
  "biography" text,
  "roles_played" int,
  "own_channel_link" text
);

CREATE TABLE "TranslatorsAnimes" (
  "translatorAnimeID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "animeID" int,
  "translatorID" int
);

CREATE TABLE "Translators" (
  "translatorID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "birthdate" date,
  "country" varchar,
  "biography" text,
  "own_channel_link" text
);

CREATE TABLE "Favourites" (
  "favID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "accountID" int,
  "animeID" int,
  "added_on" timestamp
);

ALTER TABLE "ActorsAnimes" ADD FOREIGN KEY ("animeID") REFERENCES "Animes" ("animeID");

ALTER TABLE "ActorsAnimes" ADD FOREIGN KEY ("actorID") REFERENCES "Actors" ("actorID");

ALTER TABLE "TranslatorsAnimes" ADD FOREIGN KEY ("animeID") REFERENCES "Animes" ("animeID");

ALTER TABLE "TranslatorsAnimes" ADD FOREIGN KEY ("translatorID") REFERENCES "Translators" ("translatorID");

ALTER TABLE "Favourites" ADD FOREIGN KEY ("accountID") REFERENCES "Users" ("accountID");

ALTER TABLE "Favourites" ADD FOREIGN KEY ("animeID") REFERENCES "Animes" ("animeID");